name = "ElasticArrays"
uuid = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
version = "0.4.0"

[deps]

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
