name = "ElasticArrays"
uuid = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
version = "0.3.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
